server:
  port: 8082
  servlet:
    context-path: '/vaga/'

spring:
  application:
    name: bercalini-vaga-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vaga
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO


eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

bercalini:
  api:
    url:
      candidato: 'http://bercalini-candidato-service/candidato'